# Form implementation generated from your provided layout
# You can treat this as if it were generated by pyuic6

from PyQt6 import QtCore, QtGui, QtWidgets

try:
    # Vista web para el mapa
    from PyQt6.QtWebEngineWidgets import QWebEngineView
    HAS_WEBENGINE = True
except ImportError:
    QWebEngineView = None
    HAS_WEBENGINE = False


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # === Layout principal con pestañas ===
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")

        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.mainLayout.addWidget(self.tabWidget)

        # =========================
        # TAB 1: PARADAS
        # =========================
        self.tabParadas = QtWidgets.QWidget()
        self.tabParadas.setObjectName("tabParadas")

        # Layout horizontal dentro del tab de paradas
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tabParadas)
        self.horizontalLayout.setObjectName("horizontalLayout")

        # === LEFT PANEL ===
        self.leftWidget = QtWidgets.QWidget(parent=self.tabParadas)
        self.leftLayout = QtWidgets.QVBoxLayout(self.leftWidget)
        self.leftLayout.setObjectName("leftLayout")

        # Title label
        self.titleLabel = QtWidgets.QLabel(parent=self.leftWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.leftLayout.addWidget(self.titleLabel)

        # Stop number input
        self.stopLineEdit = QtWidgets.QLineEdit(parent=self.leftWidget)
        self.stopLineEdit.setPlaceholderText("Introduce el número de parada")
        self.stopLineEdit.setObjectName("stopLineEdit")
        self.leftLayout.addWidget(self.stopLineEdit)

        # Check button
        self.checkButton = QtWidgets.QPushButton(parent=self.leftWidget)
        self.checkButton.setObjectName("checkButton")
        self.leftLayout.addWidget(self.checkButton)

        # History label
        self.historyLabel = QtWidgets.QLabel(parent=self.leftWidget)
        font2 = QtGui.QFont()
        font2.setPointSize(10)
        self.historyLabel.setFont(font2)
        self.historyLabel.setObjectName("historyLabel")
        self.leftLayout.addWidget(self.historyLabel)

        # Grid layout for recent stops
        self.recentStopsWidget = QtWidgets.QWidget(parent=self.leftWidget)
        self.recentStopsLayout = QtWidgets.QGridLayout(self.recentStopsWidget)
        self.recentStopsLayout.setObjectName("recentStopsLayout")
        self.leftLayout.addWidget(self.recentStopsWidget)

        # Add spacer
        self.leftLayout.addStretch(1)

        self.horizontalLayout.addWidget(self.leftWidget)

        # === RIGHT PANEL ===
        self.rightWidget = QtWidgets.QWidget(parent=self.tabParadas)
        self.rightLayout = QtWidgets.QVBoxLayout(self.rightWidget)
        self.rightLayout.setObjectName("rightLayout")

        # Last updated label
        self.timeLabel = QtWidgets.QLabel(parent=self.rightWidget)
        self.timeLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight)
        self.timeLabel.setObjectName("timeLabel")
        self.rightLayout.addWidget(self.timeLabel)

        # Scroll area for arrivals
        self.scrollArea = QtWidgets.QScrollArea(parent=self.rightWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 200, 400))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.rightLayout.addWidget(self.scrollArea)

        self.horizontalLayout.addWidget(self.rightWidget)

        # Añadir tab de paradas al QTabWidget
        self.tabWidget.addTab(self.tabParadas, "")

        # =========================
        # TAB 2: MAPA
        # =========================
        self.tabMapa = QtWidgets.QWidget()
        self.tabMapa.setObjectName("tabMapa")
        self.mapLayout = QtWidgets.QVBoxLayout(self.tabMapa)
        self.mapLayout.setObjectName("mapLayout")

        if HAS_WEBENGINE and QWebEngineView is not None:
            self.mapView = QWebEngineView(parent=self.tabMapa)
            self.mapView.setObjectName("mapView")
            # URL del mapa de EMT Palma (se puede cambiar por otra)
            self.mapView.setUrl(QtCore.QUrl("https://www.emtpalma.cat/es/lineas"))
            self.mapLayout.addWidget(self.mapView)
        else:
            self.mapFallbackLabel = QtWidgets.QLabel(parent=self.tabMapa)
            self.mapFallbackLabel.setObjectName("mapFallbackLabel")
            self.mapFallbackLabel.setWordWrap(True)
            self.mapLayout.addWidget(self.mapFallbackLabel)

        self.tabWidget.addTab(self.tabMapa, "")

        MainWindow.setCentralWidget(self.centralwidget)

        # === Menubar & Statusbar ===
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EMT Palma - Bus Arrivals"))
        self.titleLabel.setText(_translate("MainWindow", "EMT PALMA"))
        self.checkButton.setText(_translate("MainWindow", "Consultar parada"))
        self.historyLabel.setText(_translate("MainWindow", "Historial:"))
        self.timeLabel.setText(_translate("MainWindow", "Última actualización: -"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabParadas), _translate("MainWindow", "Paradas"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMapa), _translate("MainWindow", "Mapa"))
        if hasattr(self, "mapFallbackLabel"):
            self.mapFallbackLabel.setText(
                _translate(
                    "MainWindow",
                    "Para ver el mapa incrustado necesitas instalar el paquete PyQt6-WebEngine.\n"
                    "Ejemplo: pip install PyQt6-WebEngine",
                )
            )
