# Form implementation generated from reading ui file 'C:\Users\adrip\Documents\GitHub\EMT\uiEMT.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from view.stop_tab import StopTab
from view.lines_tab import LinesTab


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(777, 608)
        # Estilo de la ventana principal - Tema oscuro
        MainWindow.setStyleSheet("""
            QMainWindow {
                background-color: #1e1e1e;
            }
            QTabWidget::pane {
                background-color: #1e1e1e;
                border: none;
            }
            QTabBar::tab {
                background-color: #2d2d2d;
                color: #e0e0e0;
                padding: 10px 20px;
                margin-right: 2px;
                border-top-left-radius: 8px;
                border-top-right-radius: 8px;
            }
            QTabBar::tab:selected {
                background-color: #3a3a3a;
                color: #ffffff;
            }
            QTabBar::tab:hover {
                background-color: #333333;
            }
        """)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("background-color: #1e1e1e;")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        
        # Crear pestaña de paradas usando componente modular
        self.stop_tab_component = StopTab(self.centralwidget)
        self.tab_3 = self.stop_tab_component.tab
        
        # Exponer los widgets necesarios para compatibilidad con el controlador
        self.titleLabel = self.stop_tab_component.titleLabel
        self.stopLineEdit = self.stop_tab_component.stopLineEdit
        self.checkButton = self.stop_tab_component.checkButton
        self.historyLabel = self.stop_tab_component.historyLabel
        self.recentStopsLayout = self.stop_tab_component.recentStopsLayout
        self.timeLabel = self.stop_tab_component.timeLabel
        self.scrollArea = self.stop_tab_component.scrollArea
        
        self.tabWidget.addTab(self.tab_3, "")
        
        # Crear pestaña de líneas usando componente modular
        self.lines_tab_component = LinesTab(self.centralwidget)
        self.tab_4 = self.lines_tab_component.tab
        
        # Exponer los widgets necesarios para compatibilidad con el controlador
        self.label = self.lines_tab_component.label
        self.label_2 = self.lines_tab_component.label_2
        self.scrollArea_2 = self.lines_tab_component.scrollArea_2
        self.scrollArea_3 = self.lines_tab_component.scrollArea_3
        
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 777, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EMT Palma - Bus Arrivals"))
        
        # Traducir componentes modulares
        self.stop_tab_component.retranslate_ui()
        self.lines_tab_component.retranslate_ui()
        
        # Traducir textos de las pestañas
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_3), 
            _translate("MainWindow", "Paso por Parada")
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_4), 
            _translate("MainWindow", "Consulta por lineas")
        )
